/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calc.h"

bool_t
xdr_operands(XDR *xdrs, operands *objp)
{

	if (!xdr_int(xdrs, &objp->a))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->b))
		return (FALSE);
	return (TRUE);
}
